//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreData.DataObjects.BookData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookDataObjectSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookDataObjectSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookstoreData.DataObjects.BookData.BookDataObjectSQL", typeof(BookDataObjectSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	b.Id BookId, b.Title, b.Price, b.AuthorId, a.FirstName, a.LastName, s.Amount, bf.FormatType
        ///from 
        ///	Book b
        ///inner join
        ///	Author a on a.Id = b.AuthorId
        ///inner join 
        ///	Stock s on s.BookId = b.Id
        ///inner join 
        ///	BookFormat bf on bf.Id = b.FormatId
        ///.
        /// </summary>
        internal static string SELECT_ALL {
            get {
                return ResourceManager.GetString("SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	b.Id BookId, b.Title, b.Price, b.AuthorId, a.FirstName, a.LastName, s.Amount, bf.FormatType
        ///from 
        ///	Book b
        ///inner join
        ///	Author a on a.Id = b.AuthorId
        ///inner join 
        ///	Stock s on s.BookId = b.Id
        ///inner join 
        ///	BookFormat bf on bf.Id = b.FormatId
        ///where b.Id = @id.
        /// </summary>
        internal static string SELECT_BY_ID {
            get {
                return ResourceManager.GetString("SELECT_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	b.Id BookId, b.Title, b.Price, b.AuthorId, a.FirstName, a.LastName, s.Amount , bf.FormatType
        ///from 
        ///	Book b
        ///inner join
        ///	Author a on a.Id = b.AuthorId
        ///inner join
        ///	Stock s on s.BookId = b.Id
        ///inner join 
        ///	BookFormat bf on bf.Id = b.FormatId
        ///where
        ///	b.Title LIKE @searchString 
        ///	OR
        ///	a.FirstName LIKE  @searchString 
        ///	OR
        ///	a.LastName LIKE @searchString .
        /// </summary>
        internal static string SELECT_BY_NAME_OR_TITLE {
            get {
                return ResourceManager.GetString("SELECT_BY_NAME_OR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	b.Id BookId, b.Title, b.Price, b.AuthorId, a.FirstName, a.LastName, s.Amount , bf.FormatType
        ///from 
        ///	Book b
        ///inner join
        ///	Author a on a.Id = b.AuthorId
        ///inner join
        ///	Stock s on s.BookId = b.Id
        ///inner join 
        ///	BookFormat bf on bf.Id = b.FormatId
        ///ORDER BY RANDOM() 
        ///LIMIT @limit
        ///.
        /// </summary>
        internal static string SELECT_RANDOM {
            get {
                return ResourceManager.GetString("SELECT_RANDOM", resourceCulture);
            }
        }
    }
}
